# Generated by Django 4.2.14 on 2024-07-25 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('rollno', models.IntegerField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=50)),
                ('spno', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('cls', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('pw', models.CharField(max_length=50)),
            ],
        ),
    ]
